import { Board, Task, DEFAULT_COLUMNS } from "../types/task";

export const INITIAL_BOARDS: Board[] = [
  {
    id: "board-work",
    name: "工作日常",
    icon: "💼",
    description: "每日核心開發工作與專案衝刺看板",
    isDefault: true,
    columns: DEFAULT_COLUMNS,
  },
  {
    id: "board-personal",
    name: "個人生活",
    icon: "🏡",
    description: "生活雜務、健康鍛鍊與學習成長",
    columns: DEFAULT_COLUMNS,
  },
  {
    id: "board-roadmap",
    name: "產品路線圖",
    icon: "🚀",
    description: "長期里程碑與 Feature 規劃",
    columns: DEFAULT_COLUMNS,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-inbox-1",
    title: "新增記帳與多幣別換算功能",
    description: `評估接入第三方匯率 API，並在個人生活看板中增加月度統計圖表。\n\n- **透過規劃列表和使用卡片功能**，運用看板組織待處理事項\n- **透過將日曆連接至 Trello**，並排程時間以專注於完成工作\n- 並排查看收件匣、看板和規劃工具，將所有資訊整合在一起`,
    boardId: "board-work",
    columnId: "inbox",
    orderKey: "001000",
    isStarred: true, // ⭐ Starred
    tags: ["Feature", "Finance"],
    dueDate: null, // No date by default
    completed: false,
    checklist: [
      { id: "c1", title: "調研匯率 API", completed: true },
      { id: "c2", title: "設計匯率轉換 UI", completed: false },
    ],
    attachmentsCount: 1,
    coverColor: "#3b82f6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-todo-1",
    title: "深入瞭解 Trello 基本知識與流程",
    description: `並排查看收件匣、看板和規劃工具，將所有資訊整合在一起以組織待處理事項。\n\n![Trello Preview](https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60)\n\n• 支援 Markdown 粗體與清單\n• 支援貼上圖片與本地上傳`,
    boardId: "board-work",
    columnId: "todo",
    orderKey: "001000",
    isStarred: true, // ⭐ Starred
    tags: ["Trello", "UX"],
    dueDate: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    completed: false,
    checklist: [
      { id: "c3", title: "建立多看板結構", completed: true },
      { id: "c4", title: "配置色彩主題與標籤", completed: true },
      { id: "c5", title: "自訂狀態流程欄位", completed: false },
    ],
    attachmentsCount: 2,
    coverColor: "#f59e0b",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-inprog-1",
    title: "實作 Gemini 2.0 Flash 語音多模態萃取管線",
    description: "接收音訊 Blob 並以 Structured Output 解析為繁體中文結構化待辦事項。",
    boardId: "board-work",
    columnId: "in_progress",
    orderKey: "001000",
    isStarred: false,
    tags: ["AI", "Gemini"],
    dueDate: null, // Clean, no date
    completed: false,
    checklist: [
      { id: "c8", title: "接入 @google/genai SDK", completed: true },
      { id: "c9", title: "定義 JSON Schema 提示詞", completed: true },
    ],
    attachmentsCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-waiting-1",
    title: "等待 Google AI Studio 生產環境配額審核",
    description: "若有自備 API Key 可享受極速無限制語音請求速率。",
    boardId: "board-work",
    columnId: "waiting",
    orderKey: "001000",
    isStarred: false,
    tags: ["BYOK"],
    dueDate: null,
    completed: false,
    attachmentsCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-done-1",
    title: "微調 Base 44 極光漸層與毛玻璃卡片陰影",
    description: "對齊 Base 44 設計語彙，包含雙層磨砂質感與酸橙綠焦點線條。",
    boardId: "board-work",
    columnId: "done",
    orderKey: "001000",
    isStarred: false,
    tags: [],
    dueDate: null,
    completed: true,
    attachmentsCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
